[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true


[theme]
primaryColor = "#1E88E5"
base = "dark"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
