[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true


[theme]
[theme]
primaryColor = "#1E88E5"
base = "light"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

