[server]
headless = true
address = "localhost"
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
base = "light"